import React, { useMemo, useState } from 'react'
import { normalizeProgram, validateProgram, PROGRAM_GENDERS, PROGRAM_STROKES } from './competition-program.js'

export default function CompetitionProgramReview({ draft, setDraft, onPublish, onCancel, saving, sourceUrl, sourceType }) {
  const [reviewed, setReviewed] = useState(false)
  const [active, setActive] = useState(0)
  const normalized = useMemo(() => normalizeProgram(draft), [draft])
  const issues = useMemo(() => validateProgram(normalized), [normalized])
  const update = (index, field, value) => {
    setReviewed(false)
    setDraft((d) => ({ ...d, events: d.events.map((e, i) => i === index ? { ...e, [field]: value } : e) }))
  }
  const session = draft.sessions[active]
  const changeSession = (field, value) => {
    setReviewed(false)
    setDraft((d) => ({ ...d, sessions: d.sessions.map((s, i) => i === active ? { ...s, [field]: value } : s), events: field === 'label' ? d.events.map((e) => e.sessionLabel === session.label ? { ...e, sessionLabel: value } : e) : d.events }))
  }
  const move = (index, offset) => { setReviewed(false); setDraft((d) => { const events = [...d.events]; [events[index], events[index + offset]] = [events[index + offset], events[index]]; return { ...d, events } }) }
  return <section className="program-review" aria-label="Granska grenprogram" aria-busy={saving}>
    <header><p className="eyebrow">Utkast · inte sparat</p><h3>Granska grenprogrammet</h3><p>{draft.events.filter((e) => e.itemType === 'race').length} grenar · {draft.sessions.length} pass</p><small>Det sparade programmet ändras först när du godkänner. Kontrollera mot originalet — AI kan misstolka även tydliga dokument.</small></header>
    <details className="program-source"><summary>Visa originalet</summary>{sourceType.startsWith('image/') ? <img src={sourceUrl} alt="Originalet till grenprogrammet" /> : <a href={sourceUrl} target="_blank" rel="noreferrer">Öppna original-PDF i ny flik ↗</a>}</details>
    {!!draft.warnings.length && <div className="program-warning" role="status"><strong>Kontrollera särskilt</strong>{draft.warnings.map((w, i) => <p key={i}>{w}</p>)}</div>}
    {!!issues.length && <div className="program-warning" role="status"><strong>{issues.length} saker att åtgärda</strong><ul>{issues.map((issue, i) => <li key={i}>{issue.message}</li>)}</ul></div>}
    <div className="program-session-tabs" role="tablist" aria-label="Tävlingspass">{draft.sessions.map((s, i) => <button type="button" role="tab" aria-selected={active === i} key={i} onClick={() => setActive(i)}>{s.label}<span>{draft.events.filter((e) => e.sessionLabel === s.label && e.itemType === 'race').length} grenar</span></button>)}</div>
    {session && <><div className="program-session-meta"><label>Passnamn<input maxLength={60} value={session.label} onChange={(e) => changeSession('label', e.target.value)} /></label><label>Datum<input value={session.date} onChange={(e) => changeSession('date', e.target.value)} placeholder="Ej angivet" /></label><label>Insim<input type="time" value={session.warmup} onChange={(e) => changeSession('warmup', e.target.value)} /></label><label>Tävlingsstart<input type="time" value={session.start} onChange={(e) => changeSession('start', e.target.value)} /></label></div>
      <details><summary>Kontrollinventering från originalet</summary><small>Ändra bara om AI läst själva nummerkolumnen fel. Separera med komma och lämna fältet för att kontrollera.</small><label>Synliga grennummer<input key={`${active}:${session.expectedNumbers.join(',')}`} defaultValue={session.expectedNumbers.join(', ')} onBlur={(e) => changeSession('expectedNumbers', e.target.value.split(',').map((s) => s.trim()).filter(Boolean))} /></label></details></>}
    <div className="program-review-rows">{draft.events.map((row, index) => (row.sessionLabel === session?.label || active === 0 && !draft.sessions.some((s) => s.label === row.sessionLabel)) && <details key={index} className={issues.some((i) => i.row === index) ? 'needs-review' : ''}>
      <summary><span className="program-number">{row.eventNumber || 'ℹ'}</span><span><strong>{row.label || 'Rubrik saknas'}</strong><small>{row.gender} · {row.ageClass}{row.uncertain ? ' · Kontrollera' : ''}</small></span><span aria-hidden="true">＋</span></summary>
      <div className="program-row-fields"><label>Typ<select value={row.itemType} onChange={(e) => { const value = e.target.value; setReviewed(false); setDraft((d) => ({ ...d, events: d.events.map((r, i) => i !== index ? r : { ...r, itemType: value, ...(value !== 'race' ? { eventNumber: '', distanceMeters: null, stroke: 'Annat' } : {}) }) })) }}><option value="race">Gren</option><option value="pause">Paus</option><option value="award">Prisutdelning</option><option value="info">Information</option></select></label><label>Pass<select value={row.sessionLabel} onChange={(e) => update(index, 'sessionLabel', e.target.value)}>{draft.sessions.map((s) => <option key={s.label}>{s.label}</option>)}</select></label><label>Grennummer<input value={row.eventNumber} disabled={row.itemType !== 'race'} onChange={(e) => update(index, 'eventNumber', e.target.value)} /></label><label>Rubrik<input value={row.label} onChange={(e) => update(index, 'label', e.target.value)} /></label><label>Kön<select value={row.gender} onChange={(e) => update(index, 'gender', e.target.value)}>{PROGRAM_GENDERS.map((g) => <option key={g}>{g}</option>)}</select></label><label>Klass<input value={row.ageClass} onChange={(e) => update(index, 'ageClass', e.target.value)} /></label><label>Distans (totalmeter)<input type="number" disabled={row.itemType !== 'race'} value={row.distanceMeters ?? ''} onChange={(e) => update(index, 'distanceMeters', e.target.value === '' ? null : Number(e.target.value))} /></label><label>Simsätt<select disabled={row.itemType !== 'race'} value={row.stroke} onChange={(e) => update(index, 'stroke', e.target.value)}>{PROGRAM_STROKES.map((s) => <option key={s}>{s}</option>)}</select></label></div>
      <p className="program-evidence">Källrad: {row.source || 'Ingen läsbar källrad'}</p>
      {row.uncertain && <button type="button" className="secondary-button" onClick={() => update(index, 'uncertain', false)}>Jag har kontrollerat raden</button>}
      <div className="settings-actions"><button type="button" className="text-button" disabled={index === 0 || draft.events[index - 1]?.sessionLabel !== row.sessionLabel} onClick={() => move(index, -1)}>↑ Flytta upp</button><button type="button" className="text-button" disabled={index === draft.events.length - 1 || draft.events[index + 1]?.sessionLabel !== row.sessionLabel} onClick={() => move(index, 1)}>↓ Flytta ned</button></div>
      <button type="button" className="text-button" onClick={() => { setReviewed(false); setDraft((d) => ({ ...d, events: d.events.filter((_, i) => i !== index) })) }}>Ta bort felaktig rad</button>
    </details>)}</div>
    <button type="button" className="secondary-button" disabled={saving || !session} onClick={() => { setReviewed(false); setDraft((d) => { const events = [...d.events]; const at = events.reduce((last, e, i) => e.sessionLabel === session.label ? i + 1 : last, 0); events.splice(at, 0, { eventNumber: '', sessionLabel: session.label, itemType: 'race', gender: 'Alla', ageClass: 'Alla åldrar', distanceMeters: null, stroke: 'Annat', label: '', source: 'Manuellt tillagd', uncertain: true }); return { ...d, events } }) }}>＋ Lägg till saknad rad</button>
    <label className="program-review-check"><input type="checkbox" checked={reviewed} disabled={saving} onChange={(e) => setReviewed(e.target.checked)} />Jag har jämfört alla pass och eventuella varningar med originalet.</label>
    <div className="settings-actions"><button type="button" className="secondary-button" disabled={saving} onClick={onCancel}>Kasta utkast</button><button type="button" className="primary-button" disabled={saving || !reviewed || !!issues.length} onClick={() => onPublish(normalized)}>{saving ? 'Sparar…' : 'Godkänn och spara program'}</button></div>
    <small>Befintliga anmälningar behålls. En ändrad eller borttagen gren med anmälningar blockerar sparandet så att ingen anmälan försvinner.</small>
  </section>
}
