create table public.community_posts (
  id uuid primary key default gen_random_uuid(),
  author_role text not null default 'coach' check (author_role in ('coach')),
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.kudos (
  id uuid primary key default gen_random_uuid(),
  sender_profile_id uuid not null references public.profiles(id) on delete cascade,
  recipient_profile_id uuid not null references public.profiles(id) on delete cascade,
  template_key text not null check (template_key in ('great_job', 'great_energy', 'nice_technique', 'thanks', 'fun_together', 'strong_effort')),
  created_at timestamptz not null default now(),
  check (sender_profile_id <> recipient_profile_id)
);

create table public.point_events (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('daily_active', 'checkin', 'kudos_sent', 'kudos_received', 'goal_progress', 'goal_complete')),
  points integer not null check (points between 1 and 20),
  source_key text not null,
  created_at timestamptz not null default now(),
  unique (profile_id, event_type, source_key)
);

create table public.reward_levels (
  id bigint generated by default as identity primary key,
  name text not null unique,
  emoji text not null,
  min_points integer not null unique check (min_points >= 0),
  sort_order integer not null unique
);

insert into public.reward_levels (name, emoji, min_points, sort_order) values
  ('Brons', '🥉', 0, 1),
  ('Silver', '🥈', 100, 2),
  ('Guld', '🥇', 250, 3),
  ('Diamant', '💎', 500, 4);

create index community_posts_created_idx on public.community_posts (created_at desc) where deleted_at is null;
create index kudos_created_idx on public.kudos (created_at desc);
create index kudos_sender_date_idx on public.kudos (sender_profile_id, created_at desc);
create index point_events_profile_idx on public.point_events (profile_id, created_at desc);

alter table public.community_posts enable row level security;
alter table public.kudos enable row level security;
alter table public.point_events enable row level security;
alter table public.reward_levels enable row level security;

