create table if not exists app_feedback (
  id bigint generated by default as identity primary key,
  profile_id uuid references profiles(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  best_area text,
  improve_area text,
  feature_request text,
  comment text,
  created_at timestamptz not null default now()
);
create index if not exists app_feedback_created_at_idx on app_feedback(created_at desc);
